// Single source of truth for every published component in @arshad-shah/cynosure-react.
//
// Adding a new component is one row here plus a docs page; the rest is derived:
//   • `packages/react/tsup.config.ts` reads `componentEntries()` for its build map.
//   • `packages/react/package.json` exports + files arrays are regenerated by
//     `scripts/sync-component-subpaths.mjs` (runs in `prebuild`).
//   • Per-component proxy dirs (`packages/react/<slug>/package.json`) are
//     regenerated by the same script.
//   • `packages/docs/src/lib/components-manifest.ts` re-exports doc slugs.
//   • `packages/docs/astro.config.mjs` groups items by `sidebarGroup`.
//
// Slug conventions:
//   • `slug`  — kebab-case, the subpath in `@arshad-shah/cynosure-react/<slug>`
//               and the docs page slug `components/<slug>`.
//   • `entry` — basename of the dist file (`dist/<entry>.js`). Some legacy
//               entries jam together as one word (e.g. `iconbutton`); newer
//               entries match `slug`. Always preserve the existing value so
//               consumers' deep imports keep working.
//
// `sidebarGroup` controls placement in the docs sidebar. Components with
// `sidebarGroup: null` (currently every layout primitive) don't appear in the
// sidebar — they're introduced via the Foundations pages instead.

/** @typedef {'layout' | 'typography' | 'forms' | 'overlay' | 'navigation' | 'data-display' | 'feedback'} Category */
/** @typedef {'Typography' | 'Buttons' | 'Forms' | 'Feedback' | 'Overlays' | 'Navigation' | 'Data display'} SidebarGroup */
/**
 * @typedef {Object} ComponentEntry
 * @property {string} name           PascalCase identifier matching the source folder + export.
 * @property {string} slug           Subpath / docs-page slug (kebab-case).
 * @property {string} entry          Dist-file basename (`dist/<entry>.js`).
 * @property {Category} category     Source directory + default sidebar group.
 * @property {SidebarGroup | null} [sidebarGroup]  Override the sidebar bucket. `null` → not in sidebar.
 * @property {string} [sidebarLabel] Override the sidebar label (defaults to `name`).
 * @property {string} [sidebarBadge] Sidebar badge text (e.g. `'beta'`).
 * @property {string} [sourcePath]   Override the source entry (relative to `packages/react/`). Defaults to `src/<dir>/<name>/index.ts`.
 */

/** Sidebar group order — matches the docs sidebar top-to-bottom. */
export const SIDEBAR_GROUPS = /** @type {const} */ ([
  'Layout',
  'Typography',
  'Buttons',
  'Forms',
  'Feedback',
  'Overlays',
  'Navigation',
  'Data display',
]);

/** Maps each category to its source directory under `packages/react/src/`. */
const CATEGORY_DIR = /** @type {const} */ ({
  layout: 'primitives/layout',
  typography: 'typography',
  forms: 'forms',
  overlay: 'overlay',
  navigation: 'navigation',
  'data-display': 'data-display',
  feedback: 'feedback',
});

/** Default sidebar group per category. `null` skips the sidebar. */
const DEFAULT_SIDEBAR_GROUP = /** @type {const} */ ({
  layout: 'Layout',
  typography: 'Typography',
  forms: 'Forms',
  overlay: 'Overlays',
  navigation: 'Navigation',
  'data-display': 'Data display',
  feedback: 'Feedback',
});

/** @type {ComponentEntry[]} */
export const COMPONENTS = [
  // ── Layout primitives ──────────────────────────────────────────────
  { name: 'Box', slug: 'box', entry: 'box', category: 'layout' },
  { name: 'Stack', slug: 'stack', entry: 'stack', category: 'layout' },
  { name: 'Inline', slug: 'inline', entry: 'inline', category: 'layout' },
  { name: 'Flex', slug: 'flex', entry: 'flex', category: 'layout' },
  { name: 'Grid', slug: 'grid', entry: 'grid', category: 'layout' },
  { name: 'Center', slug: 'center', entry: 'center', category: 'layout' },
  { name: 'Spacer', slug: 'spacer', entry: 'spacer', category: 'layout' },
  { name: 'Divider', slug: 'divider', entry: 'divider', category: 'layout' },
  { name: 'AspectRatio', slug: 'aspect-ratio', entry: 'aspectratio', category: 'layout' },
  { name: 'Container', slug: 'container', entry: 'container', category: 'layout' },
  { name: 'Section', slug: 'section', entry: 'section', category: 'layout' },
  { name: 'SimpleGrid', slug: 'simple-grid', entry: 'simplegrid', category: 'layout' },
  { name: 'Wrap', slug: 'wrap', entry: 'wrap', category: 'layout' },

  // ── Typography ────────────────────────────────────────────────────
  { name: 'Blockquote', slug: 'blockquote', entry: 'blockquote', category: 'typography' },
  { name: 'Code', slug: 'code', entry: 'code', category: 'typography' },
  { name: 'Heading', slug: 'heading', entry: 'heading', category: 'typography' },
  { name: 'Kbd', slug: 'kbd', entry: 'kbd', category: 'typography' },
  { name: 'Link', slug: 'link', entry: 'link', category: 'typography' },
  { name: 'List', slug: 'list', entry: 'list', category: 'typography' },
  { name: 'Mark', slug: 'mark', entry: 'mark', category: 'typography' },
  { name: 'Text', slug: 'text', entry: 'text', category: 'typography' },

  // ── Buttons (lives in `forms/` and `feedback/` source-wise) ───────
  { name: 'Button', slug: 'button', entry: 'button', category: 'forms', sidebarGroup: 'Buttons' },
  {
    name: 'ButtonGroup',
    slug: 'button-group',
    entry: 'buttongroup',
    category: 'forms',
    sidebarGroup: 'Buttons',
  },
  {
    name: 'IconButton',
    slug: 'icon-button',
    entry: 'iconbutton',
    category: 'forms',
    sidebarGroup: 'Buttons',
  },
  {
    name: 'Toggle',
    slug: 'toggle',
    entry: 'toggle',
    category: 'feedback',
    sidebarGroup: 'Buttons',
  },
  {
    name: 'ToggleGroup',
    slug: 'toggle-group',
    entry: 'toggle-group',
    category: 'feedback',
    sidebarGroup: 'Buttons',
  },

  // ── Forms ─────────────────────────────────────────────────────────
  { name: 'Input', slug: 'input', entry: 'input', category: 'forms' },
  { name: 'Textarea', slug: 'textarea', entry: 'textarea', category: 'forms' },
  { name: 'NumberInput', slug: 'number-input', entry: 'numberinput', category: 'forms' },
  { name: 'SearchInput', slug: 'search-input', entry: 'searchinput', category: 'forms' },
  { name: 'PinInput', slug: 'pin-input', entry: 'pininput', category: 'forms' },
  { name: 'TagsInput', slug: 'tags-input', entry: 'tagsinput', category: 'forms' },
  { name: 'Checkbox', slug: 'checkbox', entry: 'checkbox', category: 'forms' },
  { name: 'CheckboxGroup', slug: 'checkbox-group', entry: 'checkboxgroup', category: 'forms' },
  { name: 'Radio', slug: 'radio', entry: 'radio', category: 'forms' },
  { name: 'RadioGroup', slug: 'radio-group', entry: 'radiogroup', category: 'forms' },
  { name: 'Switch', slug: 'switch', entry: 'switch', category: 'forms' },
  { name: 'ThemeToggle', slug: 'theme-toggle', entry: 'theme-toggle', category: 'forms' },
  { name: 'Select', slug: 'select', entry: 'select', category: 'forms' },
  { name: 'MultiSelect', slug: 'multi-select', entry: 'multiselect', category: 'forms' },
  { name: 'Combobox', slug: 'combobox', entry: 'combobox', category: 'forms' },
  { name: 'Slider', slug: 'slider', entry: 'slider', category: 'forms' },
  { name: 'RangeSlider', slug: 'range-slider', entry: 'rangeslider', category: 'forms' },
  { name: 'Rating', slug: 'rating', entry: 'rating', category: 'forms' },
  { name: 'Calendar', slug: 'calendar', entry: 'calendar', category: 'forms' },
  { name: 'DatePicker', slug: 'date-picker', entry: 'datepicker', category: 'forms' },
  {
    name: 'DateRangePicker',
    slug: 'date-range-picker',
    entry: 'daterangepicker',
    category: 'forms',
  },
  { name: 'TimePicker', slug: 'time-picker', entry: 'timepicker', category: 'forms' },
  { name: 'ColorPicker', slug: 'color-picker', entry: 'colorpicker', category: 'forms' },
  { name: 'FileUpload', slug: 'file-upload', entry: 'fileupload', category: 'forms' },
  { name: 'Label', slug: 'label', entry: 'label', category: 'forms' },
  { name: 'HelperText', slug: 'helper-text', entry: 'helpertext', category: 'forms' },
  { name: 'ErrorText', slug: 'error-text', entry: 'errortext', category: 'forms' },
  { name: 'Fieldset', slug: 'fieldset', entry: 'fieldset', category: 'forms' },
  // `Form` is the composition layer; `RHF` is the optional react-hook-form adapter.
  // Both live under `src/forms/Form/`, so their entries point at custom paths.
  {
    name: 'Form',
    slug: 'form',
    entry: 'form',
    category: 'forms',
    sourcePath: 'src/forms/Form/index.ts',
  },
  {
    name: 'RHF',
    slug: 'rhf',
    entry: 'rhf',
    category: 'forms',
    sidebarLabel: 'RHF',
    sourcePath: 'src/forms/Form/rhf/index.ts',
  },

  // ── Feedback ──────────────────────────────────────────────────────
  { name: 'Alert', slug: 'alert', entry: 'alert', category: 'feedback' },
  { name: 'Avatar', slug: 'avatar', entry: 'avatar', category: 'feedback' },
  { name: 'AvatarGroup', slug: 'avatar-group', entry: 'avatar-group', category: 'feedback' },
  { name: 'Badge', slug: 'badge', entry: 'badge', category: 'feedback' },
  { name: 'Callout', slug: 'callout', entry: 'callout', category: 'feedback' },
  { name: 'Chip', slug: 'chip', entry: 'chip', category: 'feedback' },
  { name: 'EmptyState', slug: 'empty-state', entry: 'empty-state', category: 'feedback' },
  { name: 'Indicator', slug: 'indicator', entry: 'indicator', category: 'feedback' },
  { name: 'Notification', slug: 'notification', entry: 'notification', category: 'feedback' },
  { name: 'Tag', slug: 'tag', entry: 'tag', category: 'feedback' },

  // ── Overlays ──────────────────────────────────────────────────────
  { name: 'AlertDialog', slug: 'alert-dialog', entry: 'alertdialog', category: 'overlay' },
  {
    name: 'CommandPalette',
    slug: 'command-palette',
    entry: 'command-palette',
    category: 'overlay',
  },
  { name: 'ContextMenu', slug: 'context-menu', entry: 'contextmenu', category: 'overlay' },
  { name: 'Dialog', slug: 'dialog', entry: 'dialog', category: 'overlay' },
  { name: 'Drawer', slug: 'drawer', entry: 'drawer', category: 'overlay' },
  { name: 'DropdownMenu', slug: 'dropdown-menu', entry: 'dropdownmenu', category: 'overlay' },
  { name: 'HoverCard', slug: 'hover-card', entry: 'hovercard', category: 'overlay' },
  { name: 'MenuBar', slug: 'menu-bar', entry: 'menubar', category: 'overlay' },
  { name: 'Popover', slug: 'popover', entry: 'popover', category: 'overlay' },
  { name: 'Toast', slug: 'toast', entry: 'toast', category: 'overlay' },
  { name: 'Tooltip', slug: 'tooltip', entry: 'tooltip', category: 'overlay' },

  // ── Navigation ────────────────────────────────────────────────────
  { name: 'Anchor', slug: 'anchor', entry: 'anchor', category: 'navigation' },
  { name: 'BackToTop', slug: 'back-to-top', entry: 'backtotop', category: 'navigation' },
  { name: 'Breadcrumb', slug: 'breadcrumb', entry: 'breadcrumb', category: 'navigation' },
  { name: 'Menu', slug: 'menu', entry: 'menu', category: 'navigation' },
  {
    name: 'NavigationMenu',
    slug: 'navigation-menu',
    entry: 'navigationmenu',
    category: 'navigation',
  },
  { name: 'Pagination', slug: 'pagination', entry: 'pagination', category: 'navigation' },
  { name: 'Sidebar', slug: 'sidebar', entry: 'sidebar', category: 'navigation' },
  { name: 'Stepper', slug: 'stepper', entry: 'stepper', category: 'navigation' },
  { name: 'Tabs', slug: 'tabs', entry: 'tabs', category: 'navigation' },

  // ── Data display ──────────────────────────────────────────────────
  { name: 'Accordion', slug: 'accordion', entry: 'accordion', category: 'data-display' },
  { name: 'Card', slug: 'card', entry: 'card', category: 'data-display' },
  { name: 'Carousel', slug: 'carousel', entry: 'carousel', category: 'data-display' },
  { name: 'Chart', slug: 'chart', entry: 'chart', category: 'data-display' },
  {
    name: 'CircularProgress',
    slug: 'circular-progress',
    entry: 'circular-progress',
    category: 'data-display',
  },
  { name: 'CodeBlock', slug: 'code-block', entry: 'code-block', category: 'data-display' },
  { name: 'Collapsible', slug: 'collapsible', entry: 'collapsible', category: 'data-display' },
  {
    name: 'DataTable',
    slug: 'data-table',
    entry: 'data-table',
    category: 'data-display',
    sidebarBadge: 'beta',
  },
  {
    name: 'LinearProgress',
    slug: 'linear-progress',
    entry: 'linear-progress',
    category: 'data-display',
  },
  { name: 'Resizable', slug: 'resizable', entry: 'resizable', category: 'data-display' },
  { name: 'ScrollArea', slug: 'scroll-area', entry: 'scroll-area', category: 'data-display' },
  { name: 'Skeleton', slug: 'skeleton', entry: 'skeleton', category: 'data-display' },
  { name: 'Spinner', slug: 'spinner', entry: 'spinner', category: 'data-display' },
  { name: 'Stat', slug: 'stat', entry: 'stat', category: 'data-display' },
  { name: 'Table', slug: 'table', entry: 'table', category: 'data-display' },
  { name: 'Timeline', slug: 'timeline', entry: 'timeline', category: 'data-display' },
  { name: 'Tree', slug: 'tree', entry: 'tree', category: 'data-display' },
];

/* ── Derived helpers ──────────────────────────────────────────────── */

/**
 * Components in the given source category, in manifest order.
 * @param {Category} category
 */
export function componentsByCategory(category) {
  return COMPONENTS.filter((c) => c.category === category);
}

/**
 * Resolve the effective sidebar group for a component. Falls back to the
 * category default; returns `null` when the component is excluded from the
 * sidebar.
 * @param {ComponentEntry} c
 */
export function sidebarGroupFor(c) {
  return c.sidebarGroup ?? DEFAULT_SIDEBAR_GROUP[c.category];
}

/**
 * Group the manifest by sidebar bucket and return entries in manifest order.
 * @returns {Record<SidebarGroup, ComponentEntry[]>}
 */
export function componentsBySidebarGroup() {
  const out = /** @type {Record<SidebarGroup, ComponentEntry[]>} */ (
    Object.fromEntries(SIDEBAR_GROUPS.map((g) => [g, []]))
  );
  for (const c of COMPONENTS) {
    const group = sidebarGroupFor(c);
    if (group) out[group].push(c);
  }
  return out;
}

/**
 * Resolve the source-file entry for a component, relative to
 * `packages/react/`.
 * @param {ComponentEntry} c
 */
export function sourceEntryFor(c) {
  return c.sourcePath ?? `src/${CATEGORY_DIR[c.category]}/${c.name}/index.ts`;
}

/**
 * tsup `entry` map keyed by dist-file basename → source path.
 * Caller composes this with the static non-component entries.
 * @returns {Record<string, string>}
 */
export function componentEntries() {
  /** @type {Record<string, string>} */
  const out = {};
  for (const c of COMPONENTS) out[c.entry] = sourceEntryFor(c);
  return out;
}

/** Every published subpath slug (`./<slug>` exports). */
export const COMPONENT_SLUGS = COMPONENTS.map((c) => c.slug);

/**
 * Slugs that ship a docs page under `src/content/docs/components/<slug>`.
 * Every manifest entry has a page — layout primitives included — so the
 * sidebar surfaces the full inventory.
 */
export const DOC_COMPONENT_SLUGS = COMPONENTS.map((c) => c.slug);
