import type { FeedbackColorScheme, FeedbackVariant } from '../shared/types.js';
import {
  ghostAccent,
  ghostDanger,
  ghostInfo,
  ghostNeutral,
  ghostSuccess,
  ghostWarning,
  outlineAccent,
  outlineDanger,
  outlineInfo,
  outlineNeutral,
  outlineSuccess,
  outlineWarning,
  softAccent,
  softDanger,
  softInfo,
  softNeutral,
  softSuccess,
  softWarning,
  solidAccent,
  solidDanger,
  solidInfo,
  solidNeutral,
  solidSuccess,
  solidWarning,
} from './Badge.css.js';

export const badgeVariantClass: Record<FeedbackVariant, Record<FeedbackColorScheme, string>> = {
  solid: {
    accent: solidAccent,
    neutral: solidNeutral,
    success: solidSuccess,
    warning: solidWarning,
    danger: solidDanger,
    info: solidInfo,
  },
  soft: {
    accent: softAccent,
    neutral: softNeutral,
    success: softSuccess,
    warning: softWarning,
    danger: softDanger,
    info: softInfo,
  },
  outline: {
    accent: outlineAccent,
    neutral: outlineNeutral,
    success: outlineSuccess,
    warning: outlineWarning,
    danger: outlineDanger,
    info: outlineInfo,
  },
  ghost: {
    accent: ghostAccent,
    neutral: ghostNeutral,
    success: ghostSuccess,
    warning: ghostWarning,
    danger: ghostDanger,
    info: ghostInfo,
  },
};
