import { appendFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname);

/**
 * Expand DTCG `typography` composites into sibling sub-tokens so they emit as
 * individual CSS custom properties (--cynosure-font-heading-1-size, etc.).
 *
 * The original typography token is dropped since it can't be serialised to a
 * single CSS value that covers every property portably.
 */
StyleDictionary.registerPreprocessor({
  name: 'cynosure/expand-typography',
  preprocessor: (dictionary) => {
    const walk = (node) => {
      if (node && typeof node === 'object' && '$type' in node && '$value' in node) {
        if (node.$type === 'typography' && node.$value && typeof node.$value === 'object') {
          const value = node.$value;
          // Propagate the original node's filePath onto every sub-token so the
          // per-platform `filter` (which keys off `token.filePath`) can still
          // decide whether to emit them. Without this SD assigns filePath
          // during source parsing, and new tokens created here would fall
          // through the filter and vanish from the CSS output.
          const filePath = node.filePath;
          const mk = (subType, subValue) => ({
            $type: subType,
            $value: subValue,
            ...(filePath ? { filePath } : {}),
          });
          const expanded = {};
          if (value.fontFamily !== undefined) {
            expanded.family = mk('fontFamily', value.fontFamily);
          }
          if (value.fontSize !== undefined) {
            expanded.size = mk('dimension', value.fontSize);
          }
          if (value.fontWeight !== undefined) {
            expanded.weight = mk('fontWeight', value.fontWeight);
          }
          if (value.lineHeight !== undefined) {
            expanded['line-height'] = mk('number', value.lineHeight);
          }
          if (value.letterSpacing !== undefined) {
            expanded['letter-spacing'] = mk('dimension', value.letterSpacing);
          }
          return expanded;
        }
        return node;
      }
      if (node && typeof node === 'object') {
        const out = {};
        for (const [key, child] of Object.entries(node)) {
          out[key] = walk(child);
        }
        return out;
      }
      return node;
    };
    return walk(dictionary);
  },
});

/**
 * DTCG fontFamily is an array of family names; flatten to a comma-separated
 * CSS font-family string with quotes around names that contain spaces.
 */
StyleDictionary.registerTransform({
  name: 'cynosure/fontFamily/css',
  type: 'value',
  filter: (token) => token.$type === 'fontFamily' || token.type === 'fontFamily',
  transform: (token) => {
    const value = token.$value ?? token.value;
    if (!Array.isArray(value)) return String(value);
    return value.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
  },
});

/**
 * DTCG cubicBezier is [x1, y1, x2, y2]; emit as `cubic-bezier(...)`.
 */
StyleDictionary.registerTransform({
  name: 'cynosure/cubicBezier/css',
  type: 'value',
  filter: (token) => token.$type === 'cubicBezier' || token.type === 'cubicBezier',
  transform: (token) => {
    const value = token.$value ?? token.value;
    if (!Array.isArray(value)) return String(value);
    return `cubic-bezier(${value.join(', ')})`;
  },
});

StyleDictionary.registerTransformGroup({
  name: 'cynosure/css',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'cynosure/fontFamily/css',
    'cynosure/cubicBezier/css',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'cynosure/ts',
  transforms: [
    'attribute/cti',
    'name/camel',
    'cynosure/fontFamily/css',
    'cynosure/cubicBezier/css',
  ],
});

StyleDictionary.registerFormat({
  name: 'cynosure/typescript-tokens',
  format: ({ dictionary }) => {
    const tree = {};
    for (const token of dictionary.allTokens) {
      const path = token.path;
      let node = tree;
      for (let i = 0; i < path.length - 1; i++) {
        const key = path[i];
        if (node[key] === undefined || typeof node[key] !== 'object') {
          node[key] = {};
        }
        node = node[key];
      }
      node[path[path.length - 1]] = token.$value ?? token.value;
    }
    return `// Generated by style-dictionary. Do not edit.\nexport const tokens = ${JSON.stringify(tree, null, 2)} as const;\nexport type Tokens = typeof tokens;\n`;
  },
});

const primitives = [
  'tokens/primitives/colors.json',
  'tokens/primitives/spacing.json',
  'tokens/primitives/typography.json',
  'tokens/primitives/radii.json',
  'tokens/primitives/shadows.json',
  'tokens/primitives/motion.json',
  'tokens/primitives/z-index.json',
];

const baseSemantic = [
  'tokens/semantic/colors.light.json',
  'tokens/semantic/spacing.json',
  'tokens/semantic/typography.json',
  'tokens/semantic/shadows.json',
  'tokens/semantic/breakpoints.json',
];

const darkSemantic = ['tokens/semantic/colors.dark.json'];

const build = async ({ name, source, include, selector }) => {
  const sourcePaths = source.map((s) => resolve(root, s));
  const includePaths = (include ?? []).map((s) => resolve(root, s));

  // `source` tokens are always emitted; `include` tokens are only referenced
  // for alias resolution. Filter output to the source set so dark.css only
  // carries the overrides.
  //
  // Style Dictionary 4.x stores `token.filePath` as the relative path it was
  // given in `source`, not the absolute resolved path. Match either form so
  // the filter is robust to that platform-specific normalization.
  const sourceSet = new Set([...source, ...sourcePaths]);
  const filter = (token) => sourceSet.has(token.filePath);

  const sd = new StyleDictionary({
    source: sourcePaths,
    include: includePaths,
    preprocessors: ['cynosure/expand-typography'],
    platforms: {
      css: {
        transformGroup: 'cynosure/css',
        buildPath: `${resolve(root, 'dist/css')}/`,
        prefix: 'cynosure',
        files: [
          {
            destination: `${name}.css`,
            format: 'css/variables',
            filter,
            options: {
              selector,
              outputReferences: true,
            },
          },
        ],
      },
      ts: {
        transformGroup: 'cynosure/ts',
        buildPath: `${resolve(root, 'src/generated')}/`,
        files: [{ destination: `${name}.ts`, format: 'cynosure/typescript-tokens' }],
      },
    },
  });
  await sd.hasInitialized;
  await sd.cleanAllPlatforms();
  await sd.buildAllPlatforms();
};

await build({
  name: 'base',
  source: [...primitives, ...baseSemantic],
  selector: ':root',
});

await build({
  name: 'dark',
  source: darkSemantic,
  include: primitives,
  selector: "[data-theme='dark']",
});

/**
 * Append a `prefers-reduced-motion` override that zeroes out the semantic
 * motion durations. Any component using `var(--cynosure-duration-motion-*)` in a
 * transition or animation automatically loses motion without code changes.
 */
const reducedMotionSnippet = `
@media (prefers-reduced-motion: reduce) {
  :root {
    --cynosure-duration-motion-micro: 0ms;
    --cynosure-duration-motion-short: 0ms;
    --cynosure-duration-motion-medium: 0ms;
    --cynosure-duration-motion-long: 0ms;
  }
}
`;

await appendFile(resolve(root, 'dist/css/base.css'), reducedMotionSnippet, 'utf8');
